package com.floralwhisper.entity;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

@Data
@TableName("site_config")
public class SiteConfig {
  @TableId
  private Long id;
  private String brandName;
  private String heroEyebrow;
  private String heroTitle;
  private String heroDescription;
  private String heroImage;
  private String primaryCtaText;
  private String secondaryCtaText;
  private String contactIntro;
  private String businessHoursText;
  private String footerDescription;
  private String brandLogo;
  private String heroSlidesJson;
  private String adminLoginSlidesJson;
  private String contactImagesJson;
  private String adminBrandTitle;
  private String adminBrandSubtitle;
  private String adminBrandDescription;
  private String homeStorySectionTitle;
  private String homeStorySectionIntro;
  private String homeStoryPrimaryLabel;
  private String homeStoryPrimaryTitle;
  private String homeStoryPrimaryDescription;
  private String homeStoryServiceLabel;
  private String homeStoryServiceDescription;
  private String homeStoryExperienceLabel;
  private String homeStoryExperienceDescription;
  private String homeStoryStoreLabel;
  private String homeStoryDetailLinkText;
  private String homeFeaturedSectionEyebrow;
  private String homeFeaturedSectionTitle;
  private String homeFeaturedSectionIntro;
  private String homeFeaturedSectionLinkText;
  private String homeServiceSectionEyebrow;
  private String homeServiceSectionTitle;
  private String homeServiceSectionIntro;
  private String homeServiceSectionLinkText;
  private String aboutStorySectionEyebrow;
  private String aboutTimelineSectionEyebrow;
  private String aboutTimelineSectionTitle;
  private String aboutTeamSectionEyebrow;
  private String aboutTeamSectionTitle;
  private String aboutTeamSectionIntro;
  private String galleryPageEyebrow;
  private String galleryPageTitle;
  private String galleryPageIntro;
  private String gallerySearchPlaceholder;
  private String galleryEmptyText;
  private String galleryLoadErrorText;
  private String contactPageTitle;
  private String contactPageSubmitText;
  private String contactSubmitSuccessText;
  private String consultButtonText;
  private String adminDashboardEyebrow;
  private String adminDashboardTitle;
  private String adminDashboardDescription;
  private String adminFlowersEyebrow;
  private String adminFlowersTitle;
  private String adminFlowersDescription;
  private String adminSettingsEyebrow;
  private String adminSettingsTitle;
  private String adminSettingsDescription;
  private String adminAiEyebrow;
  private String adminAiTitle;
  private String adminAiDescription;
  private String adminContactsEyebrow;
  private String adminContactsTitle;
  private String adminContactsDescription;
  private String adminSystemEyebrow;
  private String adminSystemTitle;
  private String adminSystemDescription;
  private String adminOperationLogsEyebrow;
  private String adminOperationLogsTitle;
  private String adminOperationLogsDescription;
}
