import type { BrandStory, Category, Flower, ShopInfo, TeamMember } from "./types";

const image = (seed: string, width = 900, height = 1100) =>
  `https://picsum.photos/seed/${seed}/${width}/${height}`;

export const categories: Category[] = [
  { id: "all", name: "全部", icon: "leaf", description: "花语时光全部作品", sort: 999 },
  { id: "wedding", name: "婚礼系列", icon: "rings", description: "仪式感与浪漫并存", sort: 100 },
  { id: "daily", name: "日常花礼", icon: "gift", description: "适合生日、探望与日常惊喜", sort: 90 },
  { id: "opening", name: "开业花篮", icon: "store", description: "明亮体面的商务花礼", sort: 80 },
  { id: "seasonal", name: "节气花束", icon: "sun", description: "顺应季节的自然花材", sort: 70 },
  { id: "custom", name: "定制花艺", icon: "scissors", description: "空间、宴会与专属主题定制", sort: 60 },
  { id: "preserved", name: "永生花系列", icon: "sparkles", description: "长久保存的温柔纪念", sort: 50 },
];

export const flowers: Flower[] = [
  {
    id: "wedding_001",
    name: "永恒之约",
    categoryId: "wedding",
    images: [image("wedding-rose-1"), image("wedding-rose-2"), image("wedding-rose-3")],
    price: 899,
    description: "以白玫瑰与淡紫绣球构成层次，适合户外婚礼、求婚和纪念日。",
    materials: ["白玫瑰", "绣球", "尤加利叶", "满天星"],
    meaning: "象征纯洁的爱情与长久承诺。",
    tags: ["婚礼", "白色系", "清新", "户外"],
    featured: true,
    sort: 100,
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "daily_001",
    name: "晨光奶油",
    categoryId: "daily",
    images: [image("daily-cream-1"), image("daily-cream-2")],
    price: 268,
    description: "奶油色玫瑰搭配洋桔梗，柔和明亮，是日常表达心意的轻盈选择。",
    materials: ["奶油玫瑰", "洋桔梗", "小菊", "银叶菊"],
    meaning: "把平凡一天变成值得收藏的片刻。",
    tags: ["生日", "奶油色", "温柔"],
    featured: true,
    sort: 95,
    createdAt: "2026-02-03T10:00:00Z",
  },
  {
    id: "opening_001",
    name: "绿野启程",
    categoryId: "opening",
    images: [image("opening-green-1"), image("opening-green-2")],
    price: 688,
    description: "绿色系叶材和跳色花材组合，适合新店开业、品牌活动和展厅布置。",
    materials: ["向日葵", "跳舞兰", "龟背竹", "散尾葵"],
    meaning: "寓意生长、繁盛与新的开始。",
    tags: ["开业", "商务", "绿色系"],
    featured: true,
    sort: 88,
    createdAt: "2026-02-14T10:00:00Z",
  },
  {
    id: "seasonal_001",
    name: "春日来信",
    categoryId: "seasonal",
    images: [image("spring-letter-1"), image("spring-letter-2")],
    price: 328,
    description: "以郁金香、风信子和小苍兰表现春天的轻盈气息。",
    materials: ["郁金香", "风信子", "小苍兰", "蕾丝花"],
    meaning: "适合把春天和问候一起送达。",
    tags: ["节气", "春日", "浅色系"],
    featured: false,
    sort: 78,
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "custom_001",
    name: "森系餐桌",
    categoryId: "custom",
    images: [image("custom-table-1", 1200, 900), image("custom-table-2", 1200, 900)],
    price: 1299,
    description: "面向私宴与品牌沙龙的桌面花艺，用自然枝叶和低饱和花材打造沉浸氛围。",
    materials: ["铁线莲", "玫瑰", "尤加利", "苔藓"],
    meaning: "让空间拥有自然呼吸感。",
    tags: ["定制", "宴会", "森系"],
    featured: false,
    sort: 72,
    createdAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "preserved_001",
    name: "月光盒子",
    categoryId: "preserved",
    images: [image("preserved-box-1"), image("preserved-box-2")],
    price: 399,
    description: "永生玫瑰与干燥花材组成礼盒，适合长期保存的纪念礼物。",
    materials: ["永生玫瑰", "兔尾草", "满天星", "绣球干花"],
    meaning: "把感谢、思念和祝福留得更久。",
    tags: ["永生花", "礼盒", "纪念"],
    featured: true,
    sort: 84,
    createdAt: "2026-04-02T10:00:00Z",
  },
  {
    id: "daily_002",
    name: "粉雾星期天",
    categoryId: "daily",
    images: [image("pink-sunday-1"), image("pink-sunday-2")],
    price: 298,
    description: "粉玫瑰和康乃馨交织出柔软雾感，适合母亲节、生日与探望。",
    materials: ["粉玫瑰", "康乃馨", "洋甘菊", "尤加利"],
    meaning: "温柔陪伴和不张扬的爱。",
    tags: ["生日", "粉色系", "探望"],
    featured: false,
    sort: 68,
    createdAt: "2026-04-16T10:00:00Z",
  },
  {
    id: "wedding_002",
    name: "暮色誓言",
    categoryId: "wedding",
    images: [image("wedding-dusk-1"), image("wedding-dusk-2")],
    price: 1099,
    description: "深粉和酒红花材营造傍晚仪式的浓郁情绪。",
    materials: ["花园玫瑰", "大丽花", "喷泉草", "桉树叶"],
    meaning: "适合表达坚定、热烈而成熟的爱。",
    tags: ["婚礼", "酒红色", "仪式"],
    featured: false,
    sort: 66,
    createdAt: "2026-04-24T10:00:00Z",
  },
];

export const shopInfo: ShopInfo = {
  name: "花语时光",
  phone: "021-6688-5200",
  wechat: "FloralWhisperTime",
  address: "上海市徐汇区衡山路 88 号 1 层",
  latitude: 31.2047,
  longitude: 121.4442,
  hours: {
    monday: { open: "09:30", close: "21:00" },
    tuesday: { open: "09:30", close: "21:00" },
    wednesday: { open: "09:30", close: "21:00" },
    thursday: { open: "09:30", close: "21:00" },
    friday: { open: "09:30", close: "21:30" },
    saturday: { open: "10:00", close: "21:30" },
    sunday: { open: "10:00", close: "20:30" },
  },
};

export const brandStory: BrandStory = {
  title: "让花束像一封慢慢抵达的信",
  subtitle: "花语时光相信，每一束花都应该有清楚的情绪和自然的呼吸。",
  content:
    "我们从季节花材出发，为婚礼、日常赠礼、商业空间和私人宴会设计花艺。店铺坚持少量精选、手工制作，用克制的色彩和舒展的结构表达真诚心意。",
  images: [image("shop-front", 1200, 800), image("florist-table", 1200, 800)],
};

export const teamMembers: TeamMember[] = [
  {
    id: "tang",
    name: "唐予安",
    title: "主理人 / 花艺设计师",
    avatar: image("florist-tang", 600, 600),
    bio: "擅长自然系婚礼花艺和空间花艺，偏爱低饱和配色。",
    sort: 1,
  },
  {
    id: "lin",
    name: "林向晚",
    title: "花束设计师",
    avatar: image("florist-lin", 600, 600),
    bio: "负责日常花礼与节气花束，让小束花也拥有完整的故事。",
    sort: 0,
  },
];
